-- 인입(ingestion) 스키마 — structuring.ingestion 도메인
-- 세션(ingestion) 1:N 업로드(ingestion_upload) / 원본 행(ingestion_record)
-- 컬럼 타입은 Hibernate(PostgreSQLDialect) 생성 스키마 기준 (ddl-auto=validate 통과용).

create table ingestion (
    id         bigint generated by default as identity primary key,
    status     varchar(255) not null check (status in ('DRAFT', 'PARSED', 'FAILED')),
    created_at timestamp(6) not null
);

create table ingestion_upload (
    id           bigint generated by default as identity primary key,
    ingestion_id bigint       not null,
    type         varchar(255) not null check (type in ('BATCH_FILE', 'FILE')),
    file_name    varchar(255) not null,
    storage_key  varchar(255) not null,
    content_type varchar(255),
    size         bigint,
    created_at   timestamp(6) not null,
    constraint fk_upload_ingestion foreign key (ingestion_id) references ingestion (id)
);

create table ingestion_record (
    id            bigint generated by default as identity primary key,
    ingestion_id  bigint not null,
    -- 원본 근거(uploadRef) — 파일 출처일 때만 채워지고, 수기 입력이면 전부 null
    upload_id     bigint,
    upload_type   varchar(255) check (upload_type in ('BATCH_FILE', 'FILE')),
    upload_row_no integer,
    -- 원문 그대로(raw) — 요구사항 §입력 파일 컬럼 9개
    doc_id         text,
    source_type    text,
    supplier       text,
    raw_item_name  text,
    spec           text,
    unit           text,
    price_before   text,
    price_after    text,
    effective_date text,
    constraint fk_record_ingestion foreign key (ingestion_id) references ingestion (id),
    constraint fk_record_upload foreign key (upload_id) references ingestion_upload (id)
);

create index idx_upload_ingestion on ingestion_upload (ingestion_id);
create index idx_record_ingestion on ingestion_record (ingestion_id);
create index idx_record_upload on ingestion_record (upload_id);
