-- 검수(inspection) 스키마 — inspection 도메인
-- 검수(inspection) 1:N 검수 레코드(inspection_record) / 변경 이력(inspection_changelog)
-- struct 1회 = Inspection 1개. 컬럼 타입은 Hibernate(PostgreSQLDialect) 생성 스키마 기준.

create table inspection (
    id           bigint generated by default as identity primary key,
    ingestion_id bigint       not null,
    created_at   timestamp(6) not null
);

create table inspection_record (
    id             bigint generated by default as identity primary key,
    inspection_id  bigint       not null,
    record_id      bigint       not null,
    -- 원본 근거(SourceRef) — 파일 출처일 때만 채워지고 수기면 null
    upload_type    varchar(255) check (upload_type in ('BATCH_FILE', 'FILE')),
    row_no         integer,
    observed       jsonb        not null,
    current_values jsonb        not null,
    flags          jsonb        not null,
    status         varchar(255) not null check (status in ('NEW', 'CONFIRMED', 'REJECTED')),
    -- 현재 검수 메모(최신 확정/반려 사유). 이력이 아니라 현재 상태이므로 레코드에 둔다.
    memo           varchar(1000),
    created_at     timestamp(6) not null,
    constraint fk_inspection_record_inspection foreign key (inspection_id) references inspection (id)
);

create table inspection_changelog (
    id            bigint generated by default as identity primary key,
    inspection_id bigint       not null,
    record_id     bigint       not null,
    type          varchar(255) not null check (type in ('EDIT', 'CONFIRM', 'REJECT')),
    from_status   varchar(255) check (from_status in ('NEW', 'CONFIRMED', 'REJECTED')),
    to_status     varchar(255) check (to_status in ('NEW', 'CONFIRMED', 'REJECTED')),
    changes       jsonb        not null,
    created_at    timestamp(6) not null,
    constraint fk_inspection_changelog_record foreign key (record_id) references inspection_record (id)
);

create index idx_inspection_ingestion on inspection (ingestion_id);
create index idx_inspection_record_inspection on inspection_record (inspection_id);
create index idx_inspection_changelog_record on inspection_changelog (record_id);
