-- 검수 인박스(inspection.inbox) — struct 1회 = Inbox 1개, 그 밑에 검수 항목 N개.
-- 컬럼 타입은 Hibernate(PostgreSQLDialect) 생성 스키마 기준 (ddl-auto=validate 통과용).

create table inbox (
    id           bigint generated by default as identity primary key,
    ingestion_id bigint       not null,
    created_at   timestamp(6) not null
);

create table inbox_item (
    id             bigint generated by default as identity primary key,
    inbox_id       bigint       not null,
    record_id      bigint       not null,
    -- 원본 근거(SourceRef) — 파일 출처일 때만 채워지고 수기면 null
    upload_type    varchar(255) check (upload_type in ('BATCH_FILE', 'FILE')),
    row_no         integer,
    observed       jsonb        not null,
    current_values jsonb        not null,
    flags          jsonb        not null,
    status         varchar(255) not null check (status in ('NEW', 'CONFIRMED', 'REJECTED')),
    created_at     timestamp(6) not null,
    constraint fk_inbox_item_inbox foreign key (inbox_id) references inbox (id)
);

create index idx_inbox_ingestion on inbox (ingestion_id);
create index idx_inbox_item_inbox on inbox_item (inbox_id);
