-- 검수(inspection) — struct 1회 = Inspection 1개, 그 밑에 검수 레코드 N개.
-- 컬럼 타입은 Hibernate(PostgreSQLDialect) 생성 스키마 기준 (ddl-auto=validate 통과용).

create table inspection (
    id           bigint generated by default as identity primary key,
    ingestion_id bigint       not null,
    created_at   timestamp(6) not null
);

create table inspection_record (
    id             bigint generated by default as identity primary key,
    inspection_id  bigint       not null,
    record_id      bigint       not null,
    -- 원본 근거(SourceRef) — 파일 출처일 때만 채워지고 수기면 null
    upload_type    varchar(255) check (upload_type in ('BATCH_FILE', 'FILE')),
    row_no         integer,
    observed       jsonb        not null,
    current_values jsonb        not null,
    flags          jsonb        not null,
    status         varchar(255) not null check (status in ('NEW', 'CONFIRMED', 'REJECTED')),
    created_at     timestamp(6) not null,
    constraint fk_inspection_record_inspection foreign key (inspection_id) references inspection (id)
);

create index idx_inspection_ingestion on inspection (ingestion_id);
create index idx_inspection_record_inspection on inspection_record (inspection_id);
