-- 검수 변경 이력(inspection_changelog) — 레코드별 편집·전이 감사 기록(append-only).
-- 컬럼 타입은 Hibernate(PostgreSQLDialect) 생성 스키마 기준 (ddl-auto=validate 통과용).

create table inspection_changelog (
    id            bigint generated by default as identity primary key,
    inspection_id bigint        not null,
    record_id     bigint        not null,
    type          varchar(255)  not null check (type in ('EDIT', 'CONFIRM', 'REJECT')),
    from_status   varchar(255)  check (from_status in ('NEW', 'CONFIRMED', 'REJECTED')),
    to_status     varchar(255)  check (to_status in ('NEW', 'CONFIRMED', 'REJECTED')),
    changes       jsonb         not null,
    created_at    timestamp(6)  not null,
    constraint fk_inspection_changelog_record foreign key (record_id) references inspection_record (id)
);

create index idx_inspection_changelog_record on inspection_changelog (record_id);
